import type { Metadata } from 'next';
import { SITE_URL as siteUrl, alternates, openGraph, twitter } from '@/lib/seo';
import './globals.css';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  // No `template`. Every page title already carries the brand ("Balsm — …",
  // "بلسم — …"), so a '%s | Balsm' suffix rendered them as
  // "Balsm — the community-owned healthcare OS | Balsm" and spent characters
  // Google would otherwise show.
  title: {
    default: 'Balsm — the community-owned healthcare OS',
    template: '%s',
  },
  description: 'The first community-owned healthcare OS for the Arab world — Arabic-first, offline-ready, and fully open source. From Egypt, to the whole Arab world.',
  authors: [{ name: 'Balsm', url: siteUrl }],
  creator: 'Balsm',
  publisher: 'Balsm',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  // All committed rasters under public/, generated by
  // scripts/generate-brand-assets.mjs. Paths carry a file extension on
  // purpose: the next-intl middleware matcher skips anything with a dot, so an
  // extensionless metadata route (/icon, /opengraph-image) never reaches its
  // handler and crawlers get a 404 instead of an image.
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '16x16 32x32 48x48' },
      { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
      { url: '/icon-512.png', type: 'image/png', sizes: '512x512' },
      { url: '/balsm-logo.svg', type: 'image/svg+xml' },
    ],
    apple: [
      { url: '/apple-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    shortcut: '/favicon.ico',
  },
  manifest: '/manifest.webmanifest',
  openGraph: openGraph({
    locale: 'ar',
    title: 'بلسم — نظام التشغيل الصحي المملوك للمجتمع',
    description: 'أول نظام تشغيل صحي مملوك للمجتمع في العالم العربي — عربيٌّ أولاً، يعمل بلا إنترنت، ومفتوح المصدر بالكامل. من مصر، إلى كل العالم العربي.',
  }),
  twitter: twitter({
    title: 'بلسم — نظام التشغيل الصحي المملوك للمجتمع',
    description: 'أول نظام تشغيل صحي مملوك للمجتمع في العالم العربي — عربيٌّ أولاً، يعمل بلا إنترنت، ومفتوح المصدر بالكامل. من مصر، إلى كل العالم العربي.',
  }),
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    // Add your verification codes when available
    // google: 'your-google-verification-code',
    // yandex: 'your-yandex-verification-code',
    // bing: 'your-bing-verification-code',
  },
  alternates: alternates('ar'),
  category: 'Healthcare Technology',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
